[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'CloudMQTT'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = './logs/cloudmqtt.log'

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[ApplicationSettings]
certFile="./certificate.pem"
keyFile="./privateKey.pem"
clientId="[ClientID]"
userName="[UserName]"
password="[Password]"
server="[serverName]"
edgeXMetaDataUri='http://localhost:48081'

eventTopic="events"
newDeviceTopic="newDevices"
commandTopic="commands"